name: dogluv_user_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  connectivity: ^2.0.2  # for check internet connectivity
  cupertino_icons: ^1.0.0
  image_picker: ^0.6.7+14 # for image pick gallery and camera
  image_cropper: ^1.3.1  #for crop image
  font_awesome_flutter: ^8.10.0 #for icons
  http: ^0.12.2 #for networking
  provider: ^4.3.2+2 #for state management
  flutter_spinkit: ^4.1.2 # for show process bar
  fluttertoast: ^7.1.5 # for toast show
  shared_preferences: ^0.5.12+4 # share preferences save data
  intro_slider: ^2.3.3 # for introduction slider page
  flutter_swiper: ^1.1.6 # for custom slider in flutter

  cached_network_image: 2.3.2+1
  firebase_storage: ^4.0.0
  giffy_dialog: ^1.8.0
  giphy_picker: ^1.0.8
  emoji_picker: ^0.1.0
  flutter_keyboard_visibility: ^3.2.2
  photo_view: ^0.5.0
  firebase_core: ^0.5.0
  firebase_database: ^4.0.0
  cloud_firestore: ^0.14.3
  nuts_activity_indicator: ^0.1.1
  file_picker: ^2.1.5
  flutter_pdfview: ^1.0.1
  path_provider: ^1.6.27
  permission_handler: ^5.0.1+1
  google_maps_webservice: ^0.0.16
  intl: ^0.16.1
  location: ^3.0.0
  url_launcher: ^5.5.3
  latlong: ^0.6.1
  geolocator: ^6.1.6
  geocoder: ^0.2.1
  google_maps_flutter: 1.0.6
  google_map_location_picker: 4.1.2
  google_maps_place_picker: ^1.0.1
  assets_audio_player: ^2.0.13+1
  cached_video_player: ^1.0.3
  video_thumbnail: ^0.2.5+1
  oktoast: ^2.1.7
  audioplayers: ^0.14.0
  webview_flutter: ^1.0.7
  timeago: ^2.0.14
  path_provider_macos: ^0.0.4+4





# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.


  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf



  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
